server:
  port: 8000

spring:
  application:
    name: oneul-backend

  datasource:
    url: jdbc:mysql://localhost:3306/oneul?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: oneul
    password: oneul1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
